### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by maxicabanillas78** [twain47/Nominatim#363]
[root@ip-172-31-41-128 Nominatim]# ./utils/setup.php --osm-file brazil-latest.osm.pbf --all
WARNING: resetting threads to 1
Create DB
createdb: could not connect to database template1: FATAL:  role "root" is not permitted to log in
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim

**Comment by mtmail** [comment]
As the installation instructions point out "You must not run the import as user www-data or root." http://wiki.openstreetmap.org/wiki/Nominatim/Installation

**Comment by maxicabanillas78** [comment]
linux apology not be used much
poderia me tell you how to enter with another user who is not the root

**Comment by mtmail** [comment]
If you're on a Debian/Ubuntu Linux have a look at https://github.com/twain47/Nominatim/tree/master/vagrant There is a commented out section how to create a user near the top.

**Comment by maxicabanillas78** [comment]
bash-4.2$ ./utils/setup.php --osm-file brazil-latest.osm.pbf --all --osm2pgsql-cache 18000 2>&1 | tee setup.log
tee: setup.log: Permission denied
WARNING: resetting threads to 1
WARNING: resetting cache memory to 1412
Create DB
Setup DB
createlang: language "plpgsql" is already installed in database "nominatim4"
CREATE EXTENSION
ERROR:  extension "postgis" already exists
ERROR: pgsql returned with error code (3)
pgsql returned with error code (3)

**Comment by maxicabanillas78** [comment]
postgres=# DROP EXTENSION postgis;
ERROR:  extension "postgis" does not exist

**Comment by maxicabanillas78** [comment]
How do I fix this last issue

**Comment by maxicabanillas78** [comment]
![capturar](https://cloud.githubusercontent.com/assets/3855804/12935771/96d94ce4-cf7f-11e5-98a5-605467841f78.PNG)

**Comment by maxicabanillas78** [comment]
As I cobras me to finish my server
please
urgent need conctato can enter by email
maxicabanillas78@hotmail.com

**Comment by mtmail** [comment]
Excuse the delay, I'm in a different timezone.

`language "plpgsql" is already installed` and `extension "postgis" already exists` are not errors. It's good they're already installed.

When you tried to `DROP EXTENSION postgis;`, did you select the `nominatim` database first? (`psql nominatim`).

The most important error seems to be `setup.log: Permission denied`. Which user tried to run the setup script and in which directory? Is it still the root directory you tried in the beginning? Maybe just the file is owned by root from a previous run and you can delete it (`sudo rm setup.log`).

What hardware (number of CPUs, RAM, discspace) and operating system are you using?

**Comment by maxicabanillas78** [comment]
![capturar](https://cloud.githubusercontent.com/assets/3855804/12951806/48db529a-cffb-11e5-85c8-4a6f1840ae93.PNG)

this is my way
delete the database
integer this user
sudo su postgres
I run


sudo su nominatim
[nominatim@ip-172-31-41-128 Nominatim]$ ./utils/setup.php --osm-file /srv/maps/ecuador-latest.osm.pbf --all
WARNING: resetting threads to 1
Create DB
Setup DB
createlang: language "plpgsql" is already installed in database "nominatim"
CREATE EXTENSION
ERROR:  extension "postgis" already exists
ERROR: pgsql returned with error code (3)
pgsql returned with error code (3)

**Comment by maxicabanillas78** [comment]
number of CPUs, RAM, discspace 
1 CPU, 2 RAM amazon hd 120gb

map Brasil

**Comment by mtmail** [comment]
Do you remember which Amazon machine image you use? Running `cat /etc/*release*` might give you the details.

I installed Ecuador on the `Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-fce3c696` without problems.

By your description you seem to run `t2.small (Variable ECUs, 1 vCPUs, 2.5 GHz, Intel Xeon Family, 2 GiB memory, EBS only)` plus additional storage.

**Comment by maxicabanillas78** [comment]
CentOS Linux release 7.2.1511 (Core)
Derived from Red Hat Enterprise Linux 7.2 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core)
CentOS Linux release 7.2.1511 (Core)
cpe:/o:centos:centos:7


you have the server on amazon you could
share a picture of the

**Comment by maxicabanillas78** [comment]
t2.small (Variable ECUs, 1 vCPUs, 2.5 GHz, Intel Xeon Family, 2 GiB memory, EBS only)

This is my server is true

**Comment by maxicabanillas78** [comment]
apology can email private
maxicabanillas78@hotmail.com

**Comment by mtmail** [comment]
I've tested Amazon's `Red Hat Enterprise Linux 7.2` and an Amazon community image called `Centos7-201507281409` now. The community image has the same output of `ls /etc/*release*` of what you posted.

While I ran into issues related to the `yum install epel` and permission denied errors on the nominatim.so file it's different errors from what you see. I'm not too familiar with selinux's permission model and I can't spend hours debugging the permission issue.

My suggestion is to try disabling selinux or try the `Ubuntu Linux 14 LTE` operating system.

With your specific error message I would have to login to your server and do more debugging. I can do that as a business (https://geocoder.opencagedata.com/contact) but not in my free time (community support).

**Comment by mtmail** [comment]
I did some more testing. The installation works with CentOS 7.1 on https://www.digitalocean.com/ if you prefer CentOS over Ubuntu.

**Comment by maxicabanillas78** [comment]
thank you my friend
and I resolved this problem on the server
change server and run

friend and I have the com Brasil add this command
./utils/setup.php --osm-file brazil-latest.osm.pbf --all
now and I added a new one
eg lower Angola
angola-latest.osm.pbf

**Comment by maxicabanillas78** [comment]
nominatim@ip-172-31-2-109:/home/ubuntu/Nominatim$ ./utils/update.php --import-file angola-latest.osm.pbf
WARNING: resetting cache memory to 1762
/usr/bin/osmosis --read-xml '/home/ubuntu/Nominatim/angola-latest.osm.pbf' --read-empty --derive-change --write-xml-change /home/ubuntu/Nominatim/data/osmosischange.osc
sh: 1: /usr/bin/osmosis: not found
ERROR: Error converting osm to osc, osmosis returned: 127

Error converting osm to osc, osmosis returned: 127

**Comment by maxicabanillas78** [comment]
nominatim@ip-172-31-2-109:/home/ubuntu/Nominatim$ ./utils/update.php --import-file angola-latest.osm.pbf
WARNING: resetting cache memory to 1642
/usr/bin/osmosis --read-xml '/home/ubuntu/Nominatim/angola-latest.osm.pbf' --read-empty --derive-change --write-xml-change /home/ubuntu/Nominatim/data/osmosischange.osc
Feb 11, 2016 6:12:31 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.40.1
Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-xml failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to parse xml file /home/ubuntu/Nominatim/angola-latest.osm.pbf.  publicId=(null), systemId=(null), lineNumber=1, columnNumber=1.
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:113)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.xml.sax.SAXParseException: Content is not allowed in prolog.
        at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
        at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:189)
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:108)
        ... 1 more

Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 3-derive-change failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: An input error has occurred, aborting.
        at org.openstreetmap.osmosis.core.store.DataPostbox.checkForInputErrors(DataPostbox.java:90)
        at org.openstreetmap.osmosis.core.store.DataPostbox.consumeCentralQueue(DataPostbox.java:160)
        at org.openstreetmap.osmosis.core.store.DataPostbox.hasNext(DataPostbox.java:237)
        at org.openstreetmap.osmosis.set.v0_6.ChangeDeriver.run(ChangeDeriver.java:158)
        at java.lang.Thread.run(Thread.java:745)

Feb 11, 2016 6:12:32 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

ERROR: Error converting osm to osc, osmosis returned: 1

Error converting osm to osc, osmosis returned: 1

**Comment by mtmail** [comment]
As pointed out in https://github.com/twain47/Nominatim/issues/365 and https://github.com/twain47/Nominatim/issues/366 you need to merge the two input files before the import. The `update.php` script import change files, but not country files.
