### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by maxicabanillas78** [twain47/Nominatim#367]
1)
osmconvert angola-latest.osm.pbf  -o=angola-latest.xml.bz2

2)
 ./utils/update.php --import-file angola-latest.xml.bz2

3)

WARNING: resetting cache memory to 1652
/usr/bin/osmosis --read-xml '/home/ubuntu/Nominatim/angola-latest.xml.bz2' --read-empty --derive-change --write-xml-change /home/ubuntu/Nominatim/data/osmosischange.osc
Feb 12, 2016 11:02:25 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.40.1
Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-xml failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read XML file /home/ubuntu/Nominatim/angola-latest.xml.bz2.
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:123)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/ubuntu/Nominatim/angola-latest.xml.bz2 (Permission denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at org.openstreetmap.osmosis.xml.v0_6.XmlReader.run(XmlReader.java:98)
        ... 1 more

Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 3-derive-change failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: An input error has occurred, aborting.
        at org.openstreetmap.osmosis.core.store.DataPostbox.checkForInputErrors(DataPostbox.java:90)
        at org.openstreetmap.osmosis.core.store.DataPostbox.consumeCentralQueue(DataPostbox.java:155)
        at org.openstreetmap.osmosis.core.store.DataPostbox.hasNext(DataPostbox.java:237)
        at org.openstreetmap.osmosis.set.v0_6.ChangeDeriver.run(ChangeDeriver.java:158)
        at java.lang.Thread.run(Thread.java:745)

Feb 12, 2016 11:02:26 AM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:31)

ERROR: Error converting osm to osc, osmosis returned: 1

Error converting osm to osc, osmosis returned: 1

**Comment by mtmail** [comment]
The `update.php` script can only process `*.osc` files, which contain differences between two datasets http://wiki.openstreetmap.org/wiki/OsmChange You can't use the script to add a new country to another country.

You can try
`osmium cat -o all.osm.pbf country1.osm.pbf country2.osm.pbf country3.osm.pbf`
and then import all.osm.pbf into Nominatim using setup.php

https://github.com/osmcode/osmium-tool is not easy to install because of the many dependencies. Expect 2-3 hours.

**Comment by lonvia** [comment]
@maxicabanillas78 May I remind you that this is a bug tracker not a free support forum, so please restrict yourself to reporting bugs with Nominatim.
